title: Tibor
author: Tibor
url: "https://thefallofjohannm.github.io"
language: "cs-cz"

logo: /assets/img/logo.png
description: Já a můj blog.
show_downloads: false
color-scheme: dark
date-format: "%d %B %Y"
permalink: /:categories/:title

sidebar:
  - name: Home
    icon: <i class="fa-solid fa-home"></i>
    link: /
  - name: About
    icon: <i class="fa-solid fa-carrot"></i>
    link: /about/
  - name: Music
    icon: <i class="fa-solid fa-gramophone"></i>
    link: /music/
  - name: Poetry
    icon: <i class="fa-solid fa-feather-pointed"></i>
    link: /poetry/
  - name: Literature
    icon: <i class="fa-solid fa-print"></i>
    link: /literature/
  - name: Visual Arts
    icon: <i class="fa-solid fa-sailboat"></i>
    link: /visualarts/
  - name: Science
    icon: <i class="fa-sharp fa-solid fa-fire"></i>
    link: /science/
  - name: Uncategorizable
    icon: <i class="fa-solid fa-blender"></i>
    link: /uncategorizable/
  - name: Atom feed
    icon: <i class="fa-solid fa-rss"></i>
    link: /feed.xml
  - name: References
    icon: <i class="fa-solid fa-address-book"></i>
    link: /references/
  - name: Repository
    icon: <i class="fa-sharp fa-solid fa-code"></i>
    link: https://github.com/thefallofjohannm/thefallofjohannm.github.io


collections:
  posts:
    output: true
  poems:
    output: true


plugins:
  - jektex


jektex:
  cache_dir: ".jekyll-cache"
  ignore: ["*.xml"]
  silent: false
  macros:
    - ["\\Q", "\\mathbb{Q}"]
    - ["\\C", "\\mathbb{C}"]

